# Generated by Django 3.2.13 on 2022-05-19 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20220519_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='sales',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='sales',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.customer'),
        ),
    ]
